// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	game "datacenter/gateway/internal/handler/game"
	public "datacenter/gateway/internal/handler/public"
	user "datacenter/gateway/internal/handler/user"
	"datacenter/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckPassMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/public/test",
					Handler: public.TestingHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/game/info/:gameId",
				Handler: game.GameInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/game/list/:platformId",
				Handler: game.GameListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/game/draw",
				Handler: game.GameDrawHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/signup",
				Handler: user.SignupHandler(serverCtx),
			},
		},
	)
}
