// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type TestingRequest struct {
}

type TestingResponse struct {
	Message string `json:"message"`
}

type Game struct {
	GameId     int64  `json:"game_id"`
	PlatformId int64  `json:"platform_id"` // 游戏平台id
	Title      string `json:"title"`       // 游戏名称
	LinkUrl    string `json:"login_url"`   // 游戏连接地址
}

type GameInfoRequest struct {
	GameId int64 `path:"gameId"`
}

type GameInfoResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    Game   `json:"data"`
}

type GameListRequest struct {
	PlatformId int64 `json:"platform_id"` // 游戏平台id
}

type GameListResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    []Game `json:"data"`
}

type GameDrawRequest struct {
	UserId int64 `json:"user_id"` // 用户id
	GameId int64 `json:"game_id"` // 游戏id
}

type GameDrawResponse struct {
	Code    int64   `json:"code"`
	Message string  `json:"message"`
	Data    []Award `json:"data"`
}

type Award struct {
	Id         int64  `json:"award_id"`    // 奖品id
	AwardName  string `json:"award_name"`  // 奖品名称
	AwardImage string `json:"award_image"` // 奖品图片
	AwardPrice string `json:"award_price"` // 奖品价格
	GameId     int64  `json:"game_id"`     // 游戏id
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResult struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type SignupRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignupResult struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}
